services:
  frontend:
    image: ghcr.io/victorcha-95/minimall-frontend:${IMAGE_TAG:-latest}
    container_name: minimall-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - appnet

  app:
    image: ghcr.io/victorcha-95/minimall-backend:${IMAGE_TAG:-latest}
    container_name: minimall-app
    restart: always
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: minimall-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - appnet

volumes:
  redis-data:

networks:
  appnet:
    driver: bridge
