spring:
  application:
    name: MiniMall

  profiles:
    default: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  issuer: minimall
  access-ttl-seconds: 600
  secret-base64: ${JWT_SECRET_BASE64}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
