spring:
  application:
    name: MiniMall
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  issuer: minimall
  secret-base64: ${JWT_SECRET_BASE64:PLEASE_OVERRIDE_IN_ENV}
  access-ttl-seconds: 3600        # 1h
  refresh-ttl-seconds: 1209600    # 14d

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
