services:
  db-test:
    image: mysql:8.4.4
    container_name: minimall-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minimall_test
    ports:
      - "3307:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    networks:
      - test-net

  app-test:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: minimall-app-test
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      E2E_DB_URL: jdbc:mysql://db-test:3306/minimall_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      E2E_DB_USERNAME: root
      E2E_DB_PASSWORD: root
    depends_on:
      - db-test
    networks:
      - test-net
    ports:
      - "8080:8080"

volumes:
  db_data_test:

networks:
  test-net:
